#ifndef MATERIAL_UI_HANDLE_DEF_H
#define MATERIAL_UI_HANDLE_DEF_H
enum MaterialOperationState
{
	MATERIAL_UNKNOW_STATE=0x000,
	MATERIAL_BROWSE_STATE =0x001,
	MATERIAL_EDIT_STATE =0x010,
	MATERIAL_CREATE_STATE =0x100
};
#endif//MATERIAL_UI_HANDLE_DEF_H